#pragma once

#include "sdkconfig.h"

//--------------------------------------------------------------------------------------------------
// WiFi Config

#define CLS_WIFI_SSID CONFIG_CLS_WIFI_SSID
#define CLS_WIFI_PASSWORD CONFIG_CLS_WIFI_PASSWORD
#define CLS_MAXIMUM_RETRY CONFIG_CLS_MAXIMUM_RETRY

#if CONFIG_CLS_WIFI_WPA3_SAE_PWE_HUNT_AND_PECK
#define CLS_WIFI_SAE_MODE WPA3_SAE_PWE_HUNT_AND_PECK
#define CLS_WIFI_H2E_IDENTIFIER ""
#elif CONFIG_CLS_WIFI_WPA3_SAE_PWE_HASH_TO_ELEMENT
#define CLS_WIFI_SAE_MODE WPA3_SAE_PWE_HASH_TO_ELEMENT
#define CLS_WIFI_H2E_IDENTIFIER CONFIG_CLS_WIFI_PW_ID
#elif CONFIG_CLS_WIFI_WPA3_SAE_PWE_BOTH
#define CLS_WIFI_SAE_MODE WPA3_SAE_PWE_BOTH
#define CLS_WIFI_H2E_IDENTIFIER CONFIG_CLS_WIFI_PW_ID
#endif

#if CONFIG_CLS_WIFI_AUTH_OPEN
#define CLS_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_OPEN
#elif CONFIG_CLS_WIFI_AUTH_WEP
#define CLS_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WEP
#elif CONFIG_CLS_WIFI_AUTH_WPA_PSK
#define CLS_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_PSK
#elif CONFIG_CLS_WIFI_AUTH_WPA2_PSK
#define CLS_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#elif CONFIG_CLS_WIFI_AUTH_WPA_WPA2_PSK
#define CLS_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA_WPA2_PSK
#elif CONFIG_CLS_WIFI_AUTH_WPA3_PSK
#define CLS_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA3_PSK
#elif CONFIG_CLS_WIFI_AUTH_WPA2_WPA3_PSK
#define CLS_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_WPA3_PSK
#elif CONFIG_CLS_WIFI_AUTH_WAPI_PSK
#define CLS_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WAPI_PSK
#endif

//--------------------------------------------------------------------------------------------------
// Camera Config

#define CLS_CAM_PIN_PWDN CONFIG_CLS_CAM_PIN_PWDN
#define CLS_CAM_PIN_RESET CONFIG_CLS_CAM_PIN_RESET
#define CLS_CAM_PIN_XCLK CONFIG_CLS_CAM_PIN_XCLK
#define CLS_CAM_PIN_SIOD CONFIG_CLS_CAM_PIN_SIOD
#define CLS_CAM_PIN_SIOC CONFIG_CLS_CAM_PIN_SIOC
#define CLS_CAM_PIN_D7 CONFIG_CLS_CAM_PIN_D7
#define CLS_CAM_PIN_D6 CONFIG_CLS_CAM_PIN_D6
#define CLS_CAM_PIN_D5 CONFIG_CLS_CAM_PIN_D5
#define CLS_CAM_PIN_D4 CONFIG_CLS_CAM_PIN_D4
#define CLS_CAM_PIN_D3 CONFIG_CLS_CAM_PIN_D3
#define CLS_CAM_PIN_D2 CONFIG_CLS_CAM_PIN_D2
#define CLS_CAM_PIN_D1 CONFIG_CLS_CAM_PIN_D1
#define CLS_CAM_PIN_D0 CONFIG_CLS_CAM_PIN_D0
#define CLS_CAM_PIN_VSYNC CONFIG_CLS_CAM_PIN_VSYNC
#define CLS_CAM_PIN_HREF CONFIG_CLS_CAM_PIN_HREF
#define CLS_CAM_PIN_PCLK CONFIG_CLS_CAM_PIN_PCLK

#define CLS_CAM_XCLK_FREQ_HZ CONFIG_CLS_CAM_XCLK_FREQ_HZ
#define CLS_CAM_JPEG_QUALITY CONFIG_CLS_CAM_JPEG_QUALITY
#define CLS_CAM_FB_COUNT CONFIG_CLS_CAM_FB_COUNT

#if CONFIG_CLS_CAM_LEDC_TIMER_0
#define CLS_CAM_LEDC_TIMER LEDC_TIMER_0
#elif CONFIG_CLS_CAM_LEDC_TIMER_1
#define CLS_CAM_LEDC_TIMER LEDC_TIMER_1
#elif CONFIG_CLS_CAM_LEDC_TIMER_2
#define CLS_CAM_LEDC_TIMER LEDC_TIMER_2
#elif CNOFIG_CLS_CAM_LEDC_TIMER_3
#define CLS_CAM_LEDC_TIMER LEDC_TIMER_3
#else
#define CLS_CAM_LEDC_TIMER LEDC_TIMER_0
#endif

#if CONFIG_CLS_CAM_LEDC_CHANNEL_0
#define CLS_CAM_LEDC_CHANNEL LEDC_CHANNEL_0
#elif CONFIG_CLS_CAM_LEDC_CHANNEL_1
#define CLS_CAM_LEDC_CHANNEL LEDC_CHANNEL_1
#elif CONFIG_CLS_CAM_LEDC_CHANNEL_2
#define CLS_CAM_LEDC_CHANNEL LEDC_CHANNEL_2
#elif CNOFIG_CLS_CAM_LEDC_CHANNEL_3
#define CLS_CAM_LEDC_CHANNEL LEDC_CHANNEL_3
#elif CNOFIG_CLS_CAM_LEDC_CHANNEL_4
#define CLS_CAM_LEDC_CHANNEL LEDC_CHANNEL_4
#elif CNOFIG_CLS_CAM_LEDC_CHANNEL_5
#define CLS_CAM_LEDC_CHANNEL LEDC_CHANNEL_5
#else
#define CLS_CAM_LEDC_CHANNEL LEDC_CHANNEL_0
#endif

#if CONFIG_CLS_CAM_PIXEL_FORMAT_RGB565
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_RGB565
#elif CONFIG_CLS_CAM_PIXEL_FORMAT_YUV422
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_YUV422
#elif CONFIG_CLS_CAM_PIXEL_FORMAT_YUV420
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_YUV420
#elif CONFIG_CLS_CAM_PIXEL_FORMAT_GRAYSCALE
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_GRAYSCALE
#elif CONFIG_CLS_CAM_PIXEL_FORMAT_JPEG
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_JPEG
#elif CONFIG_CLS_CAM_PIXEL_FORMAT_RGB888
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_RGB888
#elif CONFIG_CLS_CAM_PIXEL_FORMAT_RAW
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_RAW
#elif CONFIG_CLS_CAM_PIXEL_FORMAT_RGB444
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_RGB444
#elif CONFIG_CLS_CAM_PIXEL_FORMAT_RGB555
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_RGB555
#else
#define CLS_CAM_PIXEL_FORMAT PIXFORMAT_RGB565
#endif

#if CONFIG_CLS_CAM_FRAME_SIZE_96X96
#define CLS_CAM_FRAME_SIZE FRAMESIZE_96X96
#elif CONFIG_CLS_CAM_FRAME_SIZE_QQVGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_QQVGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_QCIF
#define CLS_CAM_FRAME_SIZE FRAMESIZE_QCIF
#elif CONFIG_CLS_CAM_FRAME_SIZE_HQVGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_HQVGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_240X240
#define CLS_CAM_FRAME_SIZE FRAMESIZE_240X240
#elif CONFIG_CLS_CAM_FRAME_SIZE_QVGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_QVGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_CIF
#define CLS_CAM_FRAME_SIZE FRAMESIZE_CIF
#elif CONFIG_CLS_CAM_FRAME_SIZE_HVGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_HVGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_VGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_VGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_SVGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_SVGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_XGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_XGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_HD
#define CLS_CAM_FRAME_SIZE FRAMESIZE_HD
#elif CONFIG_CLS_CAM_FRAME_SIZE_SXGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_SXGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_UXGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_UXGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_FHD
#define CLS_CAM_FRAME_SIZE FRAMESIZE_FHD
#elif CONFIG_CLS_CAM_FRAME_SIZE_P_HD
#define CLS_CAM_FRAME_SIZE FRAMESIZE_P_HD
#elif CONFIG_CLS_CAM_FRAME_SIZE_P_3MP
#define CLS_CAM_FRAME_SIZE FRAMESIZE_P_3MP
#elif CONFIG_CLS_CAM_FRAME_SIZE_QXGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_QXGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_QHD
#define CLS_CAM_FRAME_SIZE FRAMESIZE_QHD
#elif CONFIG_CLS_CAM_FRAME_SIZE_WQXGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_WQXGA
#elif CONFIG_CLS_CAM_FRAME_SIZE_P_FHD
#define CLS_CAM_FRAME_SIZE FRAMESIZE_P_FHD
#elif CONFIG_CLS_CAM_FRAME_SIZE_QSXGA
#define CLS_CAM_FRAME_SIZE FRAMESIZE_QSXGA
#else
#define CLS_CAM_FRAME_SIZE FRAMESIZE_INVALID
#endif

#if CONFIG_CLS_CAM_FB_LOCATION_PSRAM
#define CLS_CAM_FB_LOCATION CAMERA_FB_IN_PSRAM
#elif CONFIG_CLS_CAM_FB_LOCATION_DRAM
#define CLS_CAM_FB_LOCATION CAMERA_FB_IN_DRAM
#else
#define CLS_CAM_FB_LOCATION CAMERA_FB_IN_PSRAM
#endif

#if CONFIG_CLS_CAM_GRAB_MODE_WHEN_EMPTY
#define CLS_CAM_GRAB_MODE CAMERA_GRAB_WHEN_EMPTY
#elif CONFIG_CLS_CAM_GRAB_MODE_LATEST
#define CLS_CAM_GRAB_MODE CAMERA_GRAB_LATEST
#else
#define CLS_CAM_GRAB_MODE CAMERA_GRAB_WHEN_EMPTY
#endif

//--------------------------------------------------------------------------------------------------